(define (problem depotprob1) (:domain Depot)
(:objects
	depot0 depot1 - depot
	distributor0 distributor1 distributor2 distributor3 - distributor
	truck0 truck1 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 - crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate5)
	(at pallet1 depot1)
	(clear crate8)
	(at pallet2 distributor0)
	(clear crate4)
	(at pallet3 distributor1)
	(clear crate2)
	(at pallet4 distributor2)
	(clear crate7)
	(at pallet5 distributor3)
	(clear crate3)
	(at pallet6 depot1)
	(clear pallet6)
	(at truck0 distributor3)
	(= (current_load truck0) 0)
	(= (load_limit truck0) 411.0)
	(at truck1 depot1)
	(= (current_load truck1) 0)
	(= (load_limit truck1) 399.0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 distributor0)
	(available hoist2)
	(at hoist3 distributor1)
	(available hoist3)
	(at hoist4 distributor2)
	(available hoist4)
	(at hoist5 distributor3)
	(available hoist5)
	(at crate0 distributor1)
	(on crate0 pallet3)
	(= (weight crate0) 71)
	(at crate1 distributor2)
	(on crate1 pallet4)
	(= (weight crate1) 38)
	(at crate2 distributor1)
	(on crate2 crate0)
	(= (weight crate2) 51)
	(at crate3 distributor3)
	(on crate3 pallet5)
	(= (weight crate3) 53)
	(at crate4 distributor0)
	(on crate4 pallet2)
	(= (weight crate4) 49)
	(at crate5 depot0)
	(on crate5 pallet0)
	(= (weight crate5) 5)
	(at crate6 distributor2)
	(on crate6 crate1)
	(= (weight crate6) 99)
	(at crate7 distributor2)
	(on crate7 crate6)
	(= (weight crate7) 40)
	(at crate8 depot1)
	(on crate8 pallet1)
	(= (weight crate8) 51)
	(= (fuel-cost) 0)
)

(:goal (and
		(on crate0 crate8)
		(on crate1 crate5)
		(on crate2 pallet3)
		(on crate3 pallet0)
		(on crate4 pallet6)
		(on crate5 crate2)
		(on crate6 crate0)
		(on crate7 crate4)
		(on crate8 pallet5)
	)
)

(:metric minimize (total-time)))
