(define (problem depotprob1) (:domain Depot)
(:objects
	depot0 - depot
	distributor0 distributor1 - distributor
	truck0 - truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 - pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 - crate
	hoist0 hoist1 hoist2 hoist3 - hoist)
(:init
	(at pallet0 depot0)
	(clear crate4)
	(at pallet1 distributor0)
	(clear crate6)
	(at pallet2 distributor1)
	(clear crate8)
	(at pallet3 distributor0)
	(clear crate5)
	(at pallet4 depot0)
	(clear pallet4)
	(at pallet5 distributor0)
	(clear pallet5)
	(at pallet6 depot0)
	(clear crate7)
	(at truck0 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 distributor0)
	(available hoist1)
	(at hoist2 distributor1)
	(available hoist2)
	(at hoist3 distributor1)
	(available hoist3)
	(at crate0 distributor0)
	(on crate0 pallet1)
	(at crate1 distributor0)
	(on crate1 pallet3)
	(at crate2 distributor0)
	(on crate2 crate0)
	(at crate3 distributor0)
	(on crate3 crate1)
	(at crate4 depot0)
	(on crate4 pallet0)
	(at crate5 distributor0)
	(on crate5 crate3)
	(at crate6 distributor0)
	(on crate6 crate2)
	(at crate7 depot0)
	(on crate7 pallet6)
	(at crate8 distributor1)
	(on crate8 pallet2)
)

(:goal (and
		(on crate0 pallet1)
		(on crate1 pallet3)
		(on crate2 pallet4)
		(on crate3 pallet5)
		(on crate4 crate2)
		(on crate6 pallet6)
		(on crate7 crate3)
	)
))
